### ISSUE TITLE
Misleading link

### ISSUE THREAD

**Issue by Vrak** [jasonwebb/SurfaceMapperGUI#1]
In the readme file, the link to SurfaceMapper library does not link to the required library.
I found the library at: https://bitbucket.org/ixagon/surfacemapper

**Comment by jasonwebb** [comment]
Great work! Shortly after making this project, ixagon's site and online presence completely disappeared from the web and I was never able to locate a mirror. I'll get that readme updated shortly with that link - hopefully it stays up for a while :P 

Realistically, consider SurfaceMapperGUI to be defunct and look at it mainly for illustrative purposes. I'm not sure if there are any decent surface mapping libraries for Processing anymore, but there does seem to be several good, actively maintained addons for openFrameworks, if you're looking for a path forward :)

**Comment by jasonwebb** [comment]
Updated the URL and added a note in the README about the current state of this project and where to go to find better options.
